apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
  namespace: grade-demo
spec:
  type: NodePort
  selector:
    app: grade-submission
  ports:
  - port: 8443    # This is the port exposed by the kube-rbac-proxy   
    targetPort: https
    nodePort: 31000
