apiVersion: v1
kind: Secret
metadata:
  name: grade-sa-token
  namespace: grade-demo
  annotations:
    kubernetes.io/service-account.name: grade-sa   # This annotation links the secret to the service account
type: kubernetes.io/service-account-token  # This type indicates that the secret contains a service account token and is used by the kube-rbac-proxy to authenticate requests.

#this create a token in ecncoded base 64 in json{.data.toke.} that can be sued to authenticate the service account
#we have to create a role before using this token, the client sould be defined one.
#kl get clusterrole (clusteradmin,admin,edit...etc)
#bind the role using clusetrolebinding in servie-account
#still it gives error, cause User "system:serviceaccount:grade-demo:default" proxy (with k8'S aPIcannot create resource "tokenreviews" in API group "authentication.k8s.io" at the cluster scope
#we need to create asnother service account which permits kube-rbac-proxy to create token reviews(05-rabc-proxy.yaml)
#add in deployment the service account name to connect. 