apiVersion: v1
kind: ServiceAccount   #badge: service-account fro kube rbac-proxy
metadata:
  name: grade-service-proxy
  namespace: grade-demo
---
#i wanto define own custom cluster role tells k8's waht resouces this service account can access
#in this create "tokenreviews" in api group "authentication.k8s.io" at the cluster scope
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: grade-service-proxy-role
rules:
- apiGroups: ["authentication.k8s.io"] # a way to organise realetd k8'S objects and resources
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"] 
  resources: ["subjectaccessreviews"]
  verbs: ["create"] 


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grade-submission-proxy-binding
subjects:
- kind: ServiceAccount #who gets identity
  name: grade-service-proxy # Name is case sensitive
  namespace: grade-demo
roleRef:
  kind: ClusterRole
  name: grade-service-proxy-role # This role grants full access to the cluster, which is not recommended for production use.
  # Use a more restrictive role in production environments.
  apiGroup: rbac.authorization.k8s.io

